### ISSUE TITLE
Game front-end

### ISSUE THREAD

**Issue by nataliavelez** [nataliavelez/playable_lines#1]
**Description:** As a player, when I play the game I should see (1) the map layout (including uncrossable tiles and source/target tiles), (2) my character's position (with a highlight to distinguish it from other players), (3) everyone else's characters and their positions, (4) who's carrying water, and (5) animations when players move and load/unload water.

**Status:** So far, we've implemented the frontend for a single-player game. When a player signs on, they can see the map, their own character, and visual indicators for actions. We still need to integrate this with the multiplayer functionality to simultaneously show other players and update animations accordingly. 

**Todo:**
Single-player functionality: 
- [x] Load map layouts from json files
- [x] Add character sprite with basic walk/idle animations
- [x] Selectively activate actions when player is in front of source/target tiles & meets preconditions
- [x] Play a special animation when player activates action
- [x] Add a visual indicator when player is carrying water
- [x] Add a visual indicator to highlight the current player
- [x] Update score when player waters a target
- [x] Change map dynamically on each trial

Multiplayer functionality: 
- [x] Tint character sprite to distinguish players from one another
- [x] Set initial locations for characters _[this needs to be integrated with the game backend]_
- [x] Show animations when other players move/act

**Comment by WhiteJP** [comment]
Most of this is now done. See multiplayer branch :)

**Comment by WhiteJP** [comment]
Rest of this is now done, see multi-round branch :)
